# check if RASSM_DATASET is set
if [ -z "$RASSM_DATASET" ]; then
    echo "RASSM_DATASET is not set, please set it to the path where the dataset should be downloaded"
    exit 1
fi

mkdir -p $RASSM_DATASET
cd $RASSM_DATASET

wget https://suitesparse-collection-website.herokuapp.com/MM/ATandT/pre2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/ATandT/twotone.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Boeing/pwtk.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Hamm/hcircuit.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Hamm/scircuit.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/LPnetlib/lp_ken_18.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Ronis/xenon2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Rothberg/cfd2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Rothberg/gearbox.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Chen/pkustk14.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Kim/kim2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Norris/lung2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Norris/stomach.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Norris/torso1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Norris/torso2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Norris/torso3.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/vanHeukelum/cage12.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/vanHeukelum/cage13.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/vanHeukelum/cage14.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_shell1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_shell2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_shell3.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_shell4.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_shell5.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_shell6.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_shell7.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_shell8.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_shell9.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_IBMNA/c-73.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_IBMSDS/matrix_9.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_IBMSDS/matrix-new_3.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/barrier2-10.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/barrier2-11.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/barrier2-12.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/barrier2-1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/barrier2-2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/barrier2-3.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/barrier2-4.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/barrier2-9.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/ohne2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/para-10.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/para-4.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/para-5.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/para-6.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/para-7.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/para-8.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/para-9.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Kamvar/Stanford.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Kamvar/Stanford_Berkeley.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Tromble/language.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Hamrle/Hamrle3.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Lin/Lin.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_indef/bmw3_2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_indef/d_pretok.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_indef/darcy003.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_indef/helm2d03.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_indef/mario002.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_indef/turon_m.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_psdef/bmw7st_1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_psdef/bmwcra_1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DNVS/fcondp2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_psdef/ford2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DNVS/fullb.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DNVS/halfb.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_psdef/hood.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_psdef/inline_1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DNVS/ship_003.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DNVS/shipsec1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DNVS/shipsec5.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DNVS/shipsec8.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DNVS/troll.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DNVS/x104.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_indef/boyd2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_indef/cont-300.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/IBM_EDA/dc1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/IBM_EDA/dc2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/IBM_EDA/dc3.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/IBM_EDA/trans4.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/IBM_EDA/trans5.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/PARSEC/CO.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/PARSEC/Ga10As10H30.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/PARSEC/Ga19As19H42.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/PARSEC/Ga41As41H72.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/PARSEC/Ge87H76.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/PARSEC/Ge99H100.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/PARSEC/Si41Ge41H72.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/PARSEC/Si87H76.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/PARSEC/SiO2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Rajat/rajat21.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Rajat/rajat23.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Rajat/rajat24.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Andrianov/ins2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Andrianov/lp1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Rajat/rajat29.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Rajat/rajat30.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schmid/thermal2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Koutsovasilis/F1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/AMD/G2_circuit.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Sandia/ASIC_320k.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Sandia/ASIC_320ks.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Sandia/ASIC_680k.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Sandia/ASIC_680ks.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/AMD/G3_circuit.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/GHS_psdef/apache2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Oberwolfach/filter3D.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Oberwolfach/boneS01.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Pajek/IMDB.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Pajek/internet.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Barabasi/NotreDame_actors.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Barabasi/NotreDame_www.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Pajek/patents_main.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_IBMNA/c-big.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_0_k101.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_1_k101.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_2_k101.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_3_k101.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_4_k101.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_5_k101.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_IBMNA/c-73b.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/INPRO/msdoor.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Mittelmann/pds-70.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Mittelmann/pds-80.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Mittelmann/pds-90.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Mittelmann/pds-100.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Mittelmann/sgpf5y6.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Mittelmann/stormG2_1000.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Mittelmann/watson_1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Mittelmann/watson_2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Mittelmann/cont11_l.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Mittelmann/cont1_l.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Mittelmann/neos.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Mittelmann/neos1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Mittelmann/neos2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Mittelmann/neos3.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Meszaros/degme.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Meszaros/tp-6.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Gleich/wikipedia-20051105.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/UTEP/Dubcova3.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/BenElechi/BenElechi1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Botonakis/FEM_3D_thermal2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Wissgott/parabolic_fem.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Watson/Baumann.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Sinclair/3Dspectralwave.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Sinclair/3Dspectralwave2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/QLi/crashbasis.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/QLi/majorbasis.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Springer/ESOC.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Rajat/Raj1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/HVDC/hvdc2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Rucci/Rucci1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/McRae/ecology1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/McRae/ecology2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/QLi/largebasis.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/CEMW/t2em.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/CEMW/tmt_unsym.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/CEMW/tmt_sym.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk/nlpkkt80.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/TKK/engine.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Um/2cubes_sphere.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Forest/TF19.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_GL7d/GL7d14.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_GL7d/GL7d15.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_GL7d/GL7d16.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_GL7d/GL7d17.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_GL7d/GL7d18.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_GL7d/GL7d19.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_GL7d/GL7d20.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_GL7d/GL7d21.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_GL7d/GL7d22.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_GL7d/GL7d23.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/ch7-8-b4.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/ch7-8-b5.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/ch7-9-b3.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/ch7-9-b4.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/ch7-9-b5.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/ch8-8-b3.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/ch8-8-b4.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/ch8-8-b5.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/D6-6.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/m133-b3.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/mk13-b5.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/n4c6-b10.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/n4c6-b6.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/n4c6-b7.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/n4c6-b8.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/n4c6-b9.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/shar_te2-b2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Homology/shar_te2-b3.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Margulies/kneser_10_4_1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Margulies/wheel_601.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Relat/rel8.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/JGD_Relat/relat8.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/FreeFieldTechnologies/mono_500Hz.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Bates/sls.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/TSOPF/TSOPF_FS_b39_c30.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Lee/fem_hifreq_circuit.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Yoshiyasu/image_interp.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Yoshiyasu/mesh_deform.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Botonakis/thermomech_TC.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Botonakis/thermomech_TK.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Botonakis/thermomech_dM.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Botonakis/thermomech_dK.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Bourchtein/atmosmodd.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Bourchtein/atmosmodj.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Bourchtein/atmosmodl.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Bourchtein/atmosmodm.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Freescale/transient.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Um/offshore.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/email-EuAll.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/web-BerkStan.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/web-Google.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/web-NotreDame.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/web-Stanford.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/amazon0302.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/amazon0312.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/amazon0505.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/amazon0601.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/roadNet-CA.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/roadNet-PA.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/roadNet-TX.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/as-Skitter.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-sign-epinions.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Dziekonski/gsm_106857.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Gleich/flickr.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Gleich/usroads-48.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Gleich/usroads.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Fluorem/PR02R.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Fluorem/RM07R.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Williams/mac_econ_fwd500.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Williams/mc2depi.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Williams/cop20k_A.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Williams/webbase-1M.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Dziekonski/dielFilterV2clx.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Dziekonski/dielFilterV3clx.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/AG-Monien/wave.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/AG-Monien/debr.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/LAW/cnr-2000.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/LAW/in-2004.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/LAW/eu-2005.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/LAW/amazon-2008.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/LAW/dblp-2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/caidaRouterLevel.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/citationCiteseer.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/coAuthorsCiteseer.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/coAuthorsDBLP.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/coPapersCiteseer.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/coPapersDBLP.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n17.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n18.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n19.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/delaunay_n20.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/kron_g500-logn17.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/kron_g500-logn18.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/rgg_n_2_17_s0.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/rgg_n_2_18_s0.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/rgg_n_2_19_s0.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/rgg_n_2_20_s0.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/belgium_osm.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/luxembourg_osm.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/144.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/598a.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/auto.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/fe_ocean.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/m14b.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/IPSO/HTC_336_4438.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/IPSO/HTC_336_9129.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Janna/Fault_639.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Janna/StocF-1465.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Chevron/Chevron3.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Chevron/Chevron4.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Bodendiek/CurlCurl_1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Bodendiek/CurlCurl_2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Bodendiek/CurlCurl_3.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/G_n_pin_pout.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/preferentialAttachment.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/smallworld.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/NACA0015.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/al2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ar2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/az2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ca2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/co2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/fl2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ga2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ia2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/id2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/il2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/in2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ks2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ky2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/la2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ma2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/md2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/mi2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/mn2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/mo2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ms2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/mt2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/nc2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/nd2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ne2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/nj2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/nm2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ny2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/oh2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ok2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/or2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/pa2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/sc2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/tn2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/tx2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/ut2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/va2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/wa2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/wi2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/wv2010.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_finan512_scagr7-2c_rlfddd.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/vsp_mod2_pgp2_slptsk.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Janna/CoupCons3D.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Janna/ML_Laplace.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Janna/Transport.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/ANSYS/Delor295K.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/ANSYS/Delor338K.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Sorensen/Linux_call_graph.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Brogan/specular.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Janna/PFlow_742.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Mazaheri/bundle_adj.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Meng/iChem_Jacobian.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/com-Amazon.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/com-DBLP.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/com-Youtube.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/higgs-twitter.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/loc-Gowalla.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-Pokec.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/sx-askubuntu.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/sx-superuser.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/wiki-talk-temporal.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/wiki-topcats.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Guettel/TEM152078.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Guettel/TEM181302.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/PowerSystem/power197k.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Goodwin/Goodwin_095.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Goodwin/Goodwin_127.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Hardesty/Hardesty1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Hardesty/Hardesty2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/VLSI/nv2.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/VLSI/imagesensor.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/VLSI/power9.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/VLSI/radiation.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/VLSI/test1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/VLSI/dgreen.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/VLSI/vas_stokes_1M.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/VLSI/ss1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/VLSI/ss.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Freescale/nxp1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Martin/marine1.tar.gz
wget https://suitesparse-collection-website.herokuapp.com/MM/Precima/analytics.tar.gz

find . -name '*.tar.gz' -exec tar xvf {} \;
rm *.tar.gz

cd -

